default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 25
  username: root
  password: rootpassword
  host: db

development:
  <<: *default
  database: blog_dev

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_prod
