default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: rootpassword
  host: <%%= ENV.fetch("DB_HOST") { "db" } %>

development:
  <<: *default
  database: blog_dev

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_prod
